baseURL = "https://velokoller.github.io/"
languageCode = "de-ch"
title = "velokoller"
theme = "koller"
sectionPagesMenu = "menu"
DefaultContentLanguage = "de"
MetaDataFormat = "toml"

[params]
    ShortDateFmt = "02.01.2006"
    LongDateFmt = "2. Januar, 2006"
    SectionSort = "asc"
    Copyright = "2018 Zeno Koller, Gerold Koller"
    PrevLabel = "← zurück"
    NextLabel = "vor →"
    IndexLabel = "Index"

# [menu]
#     [[menu.main]]
#         identifier = "about"
#         name       = "Info"
#         url        = "/about"
#         weight     = 0
