baseURL = "http://velokoller.github.io"
languageCode = "de-ch"
title = "velokoller"
theme = "koller"
sectionPagesMenu = "menu"
DefaultContentLanguage = "de"
MetaDataFormat = "toml"


# [menu]
#     [[menu.main]]
#         identifier = "about"
#         name       = "Info"
#         url        = "/about"
#         weight     = 0
